<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class ProjectStatusFilterFieldsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $project_status_filter = ProjectStatusFilterField::insert([
            [
                'id' => 1,
                'type' => 'project',
                'tower_type' => 1,
                'construction_stage_id' => 0,
                'status_id' => 1,
                'field_type' => 'date',
                'field_title' => 'Expected Date of Start',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'project_expected_date_of_start',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 2,
                'type' => 'project',
                'tower_type' => 1,
                'construction_stage_id' => 0,
                'status_id' => 1,
                'field_type' => 'date',
                'field_title' => 'Expected Date of Completion',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'project_expected_date_of_completion',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 3,
                'type' => 'project',
                'tower_type' => 1,
                'construction_stage_id' => 0,
                'status_id' => 2,
                'field_type' => 'dropdown',
                'field_title' => 'Tower',
                'model' => 'Tower',
                'data_attr_type' => 'tower',
                'class_name' => 'psdd-options towers-dd',
                'name_attribute' => 'tower',
                'level' => 1,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 5,
                'type' => 'tower',
                'tower_type' => 1,
                'construction_stage_id' => 0,
                'status_id' => 1,
                'field_type' => 'date',
                'field_title' => 'Expected Date of Start',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'tower_expected_date_of_start',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 6,
                'type' => 'tower',
                'tower_type' => 1,
                'construction_stage_id' => 0,
                'status_id' => 1,
                'field_type' => 'date',
                'field_title' => 'Expected Date of Completion',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'tower_expected_date_of_completion',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 7,
                'type' => 'tower',
                'tower_type' => 1,
                'construction_stage_id' => 0,
                'status_id' => 2,
                'field_type' => 'dropdown',
                'field_title' => 'Stage of the Construction',
                'model' => 'ConstructionStage',
                'data_attr_type' => 'tower',
                'class_name' => 'construction-stages',
                'name_attribute' => 'construction_stage',
                'level' => 3,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 8,
                'type' => 'project',
                'tower_type' => 1,
                'construction_stage_id' => 0,
                'status_id' => 3,
                'field_type' => 'date',
                'field_title' => 'Date of Completion',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'project_date_of_completion',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 9,
                'type' => 'tower',
                'tower_type' => 1,
                'construction_stage_id' => 0,
                'status_id' => 3,
                'field_type' => 'date',
                'field_title' => 'Date of Completion',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'tower_date_of_completion',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 10,
                'type' => 'tower',
                'tower_type' => 1,
                'construction_stage_id' => 0,
                'status_id' => 0,
                'field_type' => 'dropdown',
                'field_title' => 'Status of the Tower',
                'model' => 'ProjectStatus',
                'data_attr_type' => 'tower',
                'class_name' => 'tower-status-dd',
                'name_attribute' => 'tower_status',
                'level' => 2,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 11,
                'type' => 'tower',
                'tower_type' => 1,
                'construction_stage_id' => 2,
                'status_id' => 0,
                'field_type' => 'dropdown',
                'field_title' => 'Select the Floors',
                'model' => 'FloorRangesPerTower',
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'floor_range',
                'level' => 4,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 12,
                'type' => 'project',
                'tower_type' => 2,
                'construction_stage_id' => 0,
                'status_id' => 1,
                'field_type' => 'date',
                'field_title' => 'Expected Date of Start',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'project_expected_date_of_start',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 13,
                'type' => 'project',
                'tower_type' => 2,
                'construction_stage_id' => 0,
                'status_id' => 1,
                'field_type' => 'date',
                'field_title' => 'Expected Date of Completion',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'project_expected_date_of_completion',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 14,
                'type' => 'project',
                'tower_type' => 2,
                'construction_stage_id' => 0,
                'status_id' => 2,
                'field_type' => 'dropdown',
                'field_title' => 'Units',
                'model' => 'Tower',
                'data_attr_type' => 'tower',
                'class_name' => 'psdd-options',
                'name_attribute' => 'tower',
                'level' => 1,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 15,
                'type' => 'tower',
                'tower_type' => 2,
                'construction_stage_id' => 0,
                'status_id' => 1,
                'field_type' => 'date',
                'field_title' => 'Expected Date of Start',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'tower_expected_date_of_start',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 16,
                'type' => 'tower',
                'tower_type' => 2,
                'construction_stage_id' => 0,
                'status_id' => 1,
                'field_type' => 'date',
                'field_title' => 'Expected Date of Completion',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'tower_expected_date_of_completion',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 17,
                'type' => 'tower',
                'tower_type' => 2,
                'construction_stage_id' => 0,
                'status_id' => 2,
                'field_type' => 'dropdown',
                'field_title' => 'Stage of the Construction',
                'model' => 'ConstructionStage',
                'data_attr_type' => 'tower',
                'class_name' => 'construction-stages',
                'name_attribute' => 'construction_stage',
                'level' => 3,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 18,
                'type' => 'project',
                'tower_type' => 2,
                'construction_stage_id' => 0,
                'status_id' => 3,
                'field_type' => 'date',
                'field_title' => 'Date of Completion',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'project_date_of_completion',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 19,
                'type' => 'tower',
                'tower_type' => 2,
                'construction_stage_id' => 0,
                'status_id' => 3,
                'field_type' => 'date',
                'field_title' => 'Date of Completion',
                'model' => null,
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'tower_date_of_completion',
                'level' => 0,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 20,
                'type' => 'tower',
                'tower_type' => 2,
                'construction_stage_id' => 0,
                'status_id' => 0,
                'field_type' => 'dropdown',
                'field_title' => 'Status of the Unit',
                'model' => 'ProjectStatus',
                'data_attr_type' => 'tower',
                'class_name' => null,
                'name_attribute' => 'tower_status',
                'level' => 2,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
            [
                'id' => 21,
                'type' => 'tower',
                'tower_type' => 2,
                'construction_stage_id' => 2,
                'status_id' => 0,
                'field_type' => 'dropdown',
                'field_title' => 'Select the Floors',
                'model' => 'FloorRangesPerTower',
                'data_attr_type' => null,
                'class_name' => null,
                'name_attribute' => 'floor_range',
                'level' => 4,
                'created_at' => '2023-06-13 23:20:24',
                'updated_at' => '2023-06-13 23:20:24',
            ],
        ]);

        DB::table('project_status_filter_fields')->insert($data);
    }
}
