<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AmenityOption;

class propertyAmenityOptionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Amenity_option = AmenityOption::insert([
            [
                'id' => 71,
                'property_amenity_id' => 10,
                'name' => 'Modern Lobby and Reception',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 72,
                'property_amenity_id' => 10,
                'name' => 'High-Speed Elevators',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 73,
                'property_amenity_id' => 10,
                'name' => 'Security and Access Control',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 74,
                'property_amenity_id' => 10,
                'name' => 'Business Center',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 75,
                'property_amenity_id' => 10,
                'name' => 'Fitness Center',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 76,
                'property_amenity_id' => 10,
                'name' => ' Cafeteria or Food Court',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 77,
                'property_amenity_id' => 10,
                'name' => 'Retail Spaces',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 78,
                'property_amenity_id' => 10,
                'name' => 'Outdoor Seating Areas',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 79,
                'property_amenity_id' => 10,
                'name' => 'Smart Building Technology',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 80,
                'property_amenity_id' => 10,
                'name' => 'Parking Facilities',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 81,
                'property_amenity_id' => 10,
                'name' => 'High-Speed Internet Connectivity',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 82,
                'property_amenity_id' => 10,
                'name' => 'Lounge Areas',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 83,
                'property_amenity_id' => 10,
                'name' => 'Event and Conference Facilities',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 84,
                'property_amenity_id' => 10,
                'name' => 'Green Features',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 85,
                'property_amenity_id' => 10,
                'name' => 'Backup Power Supply',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 86,
                'property_amenity_id' => 10,
                'name' => 'Maintenance and Cleaning Services',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 87,
                'property_amenity_id' => 10,
                'name' => 'HVAC System',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 88,
                'property_amenity_id' => 10,
                'name' => 'Art and Aesthetic Elements',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 89,
                'property_amenity_id' => 10,
                'name' => 'ATM and Banking Services',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 90,
                'property_amenity_id' => 10,
                'name' => 'Shuttle Services',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 91,
                'property_amenity_id' => 10,
                'name' => 'Yoga/Meditation Room',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 92,
                'property_amenity_id' => 10,
                'name' => 'Game Room',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 93,
                'property_amenity_id' => 10,
                'name' => 'Library or Reading Room',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 94,
                'property_amenity_id' => 10,
                'name' => 'Daycare Facilities',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 95,
                'property_amenity_id' => 10,
                'name' => 'Rooftop Terrace',
                'status' => '1',
                'sort_by' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
